// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cttmxkarprnorzcdlfmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0dG14a2FycHJub3J6Y2RsZm10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4OTM2NDYsImV4cCI6MjA2MDQ2OTY0Nn0.0kwqxWkNGqVLwhQMJgnWNysh570X8m3Zmvg0a3iE7e0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);